# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hex_pb_package.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hex_pb_package.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1aproto/hex_pb_package.proto\"%\n\x07Package\x12\x1a\n\x08releases\x18\x01 \x03(\x0b\x32\x08.Release\"s\n\x07Release\x12\x0f\n\x07version\x18\x01 \x02(\t\x12\x10\n\x08\x63hecksum\x18\x02 \x02(\x0c\x12!\n\x0c\x64\x65pendencies\x18\x03 \x03(\x0b\x32\x0b.Dependency\x12\"\n\x07retired\x18\x04 \x01(\x0b\x32\x11.RetirementStatus\"F\n\x10RetirementStatus\x12!\n\x06reason\x18\x01 \x02(\x0e\x32\x11.RetirementReason\x12\x0f\n\x07message\x18\x02 \x01(\t\"d\n\nDependency\x12\x0f\n\x07package\x18\x01 \x02(\t\x12\x13\n\x0brequirement\x18\x02 \x02(\t\x12\x10\n\x08optional\x18\x03 \x01(\x08\x12\x0b\n\x03\x61pp\x18\x04 \x01(\t\x12\x11\n\tnamespace\x18\x05 \x01(\t*}\n\x10RetirementReason\x12\x11\n\rRETIRED_OTHER\x10\x00\x12\x13\n\x0fRETIRED_INVALID\x10\x01\x12\x14\n\x10RETIRED_SECURITY\x10\x02\x12\x16\n\x12RETIRED_DEPRECATED\x10\x03\x12\x13\n\x0fRETIRED_RENAMED\x10\x04')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_RETIREMENTREASON = _descriptor.EnumDescriptor(
  name='RetirementReason',
  full_name='RetirementReason',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RETIRED_OTHER', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETIRED_INVALID', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETIRED_SECURITY', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETIRED_DEPRECATED', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RETIRED_RENAMED', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=360,
  serialized_end=485,
)
_sym_db.RegisterEnumDescriptor(_RETIREMENTREASON)

RetirementReason = enum_type_wrapper.EnumTypeWrapper(_RETIREMENTREASON)
RETIRED_OTHER = 0
RETIRED_INVALID = 1
RETIRED_SECURITY = 2
RETIRED_DEPRECATED = 3
RETIRED_RENAMED = 4



_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='releases', full_name='Package.releases', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=67,
)


_RELEASE = _descriptor.Descriptor(
  name='Release',
  full_name='Release',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='Release.version', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='checksum', full_name='Release.checksum', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dependencies', full_name='Release.dependencies', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retired', full_name='Release.retired', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=184,
)


_RETIREMENTSTATUS = _descriptor.Descriptor(
  name='RetirementStatus',
  full_name='RetirementStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reason', full_name='RetirementStatus.reason', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='RetirementStatus.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=256,
)


_DEPENDENCY = _descriptor.Descriptor(
  name='Dependency',
  full_name='Dependency',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='package', full_name='Dependency.package', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='requirement', full_name='Dependency.requirement', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='optional', full_name='Dependency.optional', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='app', full_name='Dependency.app', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='Dependency.namespace', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=358,
)

_PACKAGE.fields_by_name['releases'].message_type = _RELEASE
_RELEASE.fields_by_name['dependencies'].message_type = _DEPENDENCY
_RELEASE.fields_by_name['retired'].message_type = _RETIREMENTSTATUS
_RETIREMENTSTATUS.fields_by_name['reason'].enum_type = _RETIREMENTREASON
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE
DESCRIPTOR.message_types_by_name['Release'] = _RELEASE
DESCRIPTOR.message_types_by_name['RetirementStatus'] = _RETIREMENTSTATUS
DESCRIPTOR.message_types_by_name['Dependency'] = _DEPENDENCY
DESCRIPTOR.enum_types_by_name['RetirementReason'] = _RETIREMENTREASON

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGE,
  __module__ = 'proto.hex_pb_package_pb2'
  # @@protoc_insertion_point(class_scope:Package)
  ))
_sym_db.RegisterMessage(Package)

Release = _reflection.GeneratedProtocolMessageType('Release', (_message.Message,), dict(
  DESCRIPTOR = _RELEASE,
  __module__ = 'proto.hex_pb_package_pb2'
  # @@protoc_insertion_point(class_scope:Release)
  ))
_sym_db.RegisterMessage(Release)

RetirementStatus = _reflection.GeneratedProtocolMessageType('RetirementStatus', (_message.Message,), dict(
  DESCRIPTOR = _RETIREMENTSTATUS,
  __module__ = 'proto.hex_pb_package_pb2'
  # @@protoc_insertion_point(class_scope:RetirementStatus)
  ))
_sym_db.RegisterMessage(RetirementStatus)

Dependency = _reflection.GeneratedProtocolMessageType('Dependency', (_message.Message,), dict(
  DESCRIPTOR = _DEPENDENCY,
  __module__ = 'proto.hex_pb_package_pb2'
  # @@protoc_insertion_point(class_scope:Dependency)
  ))
_sym_db.RegisterMessage(Dependency)


# @@protoc_insertion_point(module_scope)
