# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hex_pb_signed.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hex_pb_signed.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x19proto/hex_pb_signed.proto\",\n\x06Signed\x12\x0f\n\x07payload\x18\x01 \x02(\x0c\x12\x11\n\tsignature\x18\x02 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIGNED = _descriptor.Descriptor(
  name='Signed',
  full_name='Signed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='Signed.payload', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='signature', full_name='Signed.signature', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['Signed'] = _SIGNED

Signed = _reflection.GeneratedProtocolMessageType('Signed', (_message.Message,), dict(
  DESCRIPTOR = _SIGNED,
  __module__ = 'proto.hex_pb_signed_pb2'
  # @@protoc_insertion_point(class_scope:Signed)
  ))
_sym_db.RegisterMessage(Signed)


# @@protoc_insertion_point(module_scope)
