# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/hex_pb_versions.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/hex_pb_versions.proto',
  package='',
  syntax='proto2',
  serialized_pb=_b('\n\x1bproto/hex_pb_versions.proto\"&\n\x08Versions\x12\x1a\n\x08packages\x18\x01 \x03(\x0b\x32\x08.Package\"Q\n\x07Package\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x10\n\x08versions\x18\x02 \x03(\t\x12\x13\n\x07retired\x18\x03 \x03(\x05\x42\x02\x10\x01\x12\x11\n\tnamespace\x18\x04 \x01(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_VERSIONS = _descriptor.Descriptor(
  name='Versions',
  full_name='Versions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='packages', full_name='Versions.packages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=69,
)


_PACKAGE = _descriptor.Descriptor(
  name='Package',
  full_name='Package',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Package.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='versions', full_name='Package.versions', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='retired', full_name='Package.retired', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='namespace', full_name='Package.namespace', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=152,
)

_VERSIONS.fields_by_name['packages'].message_type = _PACKAGE
DESCRIPTOR.message_types_by_name['Versions'] = _VERSIONS
DESCRIPTOR.message_types_by_name['Package'] = _PACKAGE

Versions = _reflection.GeneratedProtocolMessageType('Versions', (_message.Message,), dict(
  DESCRIPTOR = _VERSIONS,
  __module__ = 'proto.hex_pb_versions_pb2'
  # @@protoc_insertion_point(class_scope:Versions)
  ))
_sym_db.RegisterMessage(Versions)

Package = _reflection.GeneratedProtocolMessageType('Package', (_message.Message,), dict(
  DESCRIPTOR = _PACKAGE,
  __module__ = 'proto.hex_pb_versions_pb2'
  # @@protoc_insertion_point(class_scope:Package)
  ))
_sym_db.RegisterMessage(Package)


_PACKAGE.fields_by_name['retired'].has_options = True
_PACKAGE.fields_by_name['retired']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
